<a href="https://colab.research.google.com/github/111202415893-source/machine-learning/blob/main/latih1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world!")   # mode skrip

Hello world!


# New Section

***NumPy***

In [ ]:
height = [1.84, 1.79, 1.82, 1.90, 1.80]

In [ ]:
famz = ["Abe", 1.84, "Beb", 1.79, "Cory", 1.82, "Dad", 1.90]

In [ ]:
weight = [66.5, 60.3, 64.7, 89.5, 69.8]

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

hasil = a + b
print(hasil)

[5 7 9]


In [ ]:
import numpy as np

np_height = np.array(height)
type(np_height)

numpy.ndarray

In [ ]:
np_weight = np.array(weight)
np_weight

array([66.5, 60.3, 64.7, 89.5, 69.8])

In [ ]:
bmi = np_weight / np_height ** 2
type(np_weight)

numpy.ndarray

In [ ]:
bmi

array([19.64201323, 18.81963734, 19.53266514, 24.79224377, 21.54320988])

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [ ]:
np_height = np.array([1.84, 1.79, 1.82, 1.9, 1.8])
np_weight = np.array([66.5, 60.3, 64.7, 89.5, 69.8])
type(np_height)
type(np_weight)

numpy.ndarray

In [ ]:
np_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
np_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np_2d.shape

(2, 5)